# Generated by Django 2.2.5 on 2020-05-04 19:55

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DadosEmpresa',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mes', models.CharField(max_length=100, verbose_name='Mes')),
                ('ano_2018', models.CharField(max_length=100, verbose_name='Ano 2018')),
                ('ano_2019', models.CharField(max_length=100, verbose_name='Ano 2019')),
            ],
        ),
    ]
